nobase_mero_include_HEADERS += rm/rm.h \
			       rm/rm_fops.h \
			       rm/rm_foms.h \
			       rm/rm_ff.h
                                  
mero_libmero_la_SOURCES     += rm/rm_fops.c \
			       rm/rm.c \
			       rm/rm_foms.c \
			       rm/rm_ff.c

FF_FILES                    += rm/rm_ff.h

EXTRA_DIST                  += rm.ff

CLEANFILES                  += rm/rm_ff.h \
                               rm/rm_ff.c
