#
# Halon build
#
---
- name: dynamically load variables depending on the OS type
  include_vars: '{{ item  }}'
  with_first_found: '{{ ansible_os_family }}.yml'
  tags:
    - halon
    - get-stack

- name: configure 'Haskell Stack' repository
  yum_repository:
    name:        petersen-stack
    file:        petersen-stack-epel-7
    description: Copr repo for stack owned by petersen
    baseurl:     https://copr-be.cloud.fedoraproject.org/results/petersen/stack/epel-7-$basearch/
    gpgcheck:    no
  when: ansible_os_family == 'RedHat'
  tags: halon

- name: enable get-stack.sh
  set_fact:
    halon_build_deps_pkgs: '{{ halon_build_deps_pkgs | difference("stack") }}'
  tags:
    - get-stack
    - never

- name: install latest 'Haskell Stack' with get-stack.sh script
  when: '"stack" not in halon_build_deps_pkgs'
  block:
    - name: download get-stack.sh
      get_url:
        url:  https://get.haskellstack.org
        dest: /tmp/get-stack.sh
        mode: 0755

    - name: run get-stack.sh
      command: /tmp/get-stack.sh
      args:
        creates: /usr/local/bin/stack
  tags:
    - halon
    - get-stack

- name: install Halon build-time dependencies
  package:
    state: present
    name:  '{{ halon_build_deps_pkgs }}'
  tags:
    - halon
    - breaks-dry-run

# RabbitMQ is needed for some of the Halon tests
- name: install RabbitMQ
  package: state=present name=rabbitmq-server
  tags:
    - halon
    - rabbitmq
    - breaks-dry-run

- name: start RabbitMQ
  service: name=rabbitmq-server state=started enabled=yes
  tags:
    - halon
    - rabbitmq
    - start-services

- name: install RabbitMQ cookie
  copy:
    src: /var/lib/rabbitmq/.erlang.cookie
    remote_src: yes
    dest:  ~{{ item }}/
    owner: '{{ item }}'
    group: '{{ item }}'
    mode:  0400
  with_items:
    - root
    - vagrant
  tags:
    - halon
    - rabbitmq
