/* -*- C -*- */
/*
 * COPYRIGHT 2011 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Nikita Danilov <nikita_danilov@xyratex.com>
 * Original creation date: 08/04/2010
 */

#ifndef __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_
#define __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_

#include <linux/types.h>

#define C2_TYPES_UINT_MAX(bits) ((uint ## bits ## _t)((uint ## bits ## _t) 0))
#define C2_TYPES_INT_MAX(bits) ((int ## bits ## _t)((uint ## bits ## _t)0) >> 1)
#define C2_TYPES_INT_MIN(bits) ((int ## bits ## _t)(-(INT ## bits ## _MAX) - 1))

#define UINT8_MAX  C2_TYPES_UINT_MAX(8)	 /* 0xFF */
#define INT8_MIN   C2_TYPES_INT_MIN(8)	 /* 0x80 */
#define INT8_MAX   C2_TYPES_INT_MAX(8)	 /* 0x7F */
#define UINT16_MAX C2_TYPES_UINT_MAX(16) /* 0xFFFF */
#define INT16_MIN  C2_TYPES_INT_MIN(16)	 /* 0x8000 */
#define INT16_MAX  C2_TYPES_INT_MAX(16)	 /* 0x7FFF */
#define UINT32_MAX C2_TYPES_UINT_MAX(32) /* 0xFFFFFFFF */
#define INT32_MIN  C2_TYPES_INT_MIN(32)	 /* 0x80000000 */
#define INT32_MAX  C2_TYPES_INT_MAX(32)	 /* 0x7FFFFFFF */
#define UINT64_MAX C2_TYPES_UINT_MAX(64) /* 0xFFFFFFFFFFFFFFFF */
#define INT64_MIN  C2_TYPES_INT_MIN(64)	 /* 0x8000000000000000 */
#define INT64_MAX  C2_TYPES_INT_MAX(64)	 /* 0x7FFFFFFFFFFFFFFF */

/* __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_ */
#endif
/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
