/* -*- C -*- */
/*
 * COPYRIGHT 2012 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Nikita Danilov <nikita_danilov@xyratex.com>
 * Original creation date: 08/04/2010
 */

#pragma once

#ifndef __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_
#define __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_

#include <linux/types.h>

#define UINT32_MAX ((uint32_t)(~((uint32_t) 0)))  /* 0xFFFFFFFF */
#define UINT64_MAX ((uint64_t)(~((uint64_t) 0)))  /* 0xFFFFFFFFFFFFFFFF */
#define INT64_MAX ((int64_t)((~(uint64_t)0) >> 1))  /* 0x3FFFFFFFFFFFFFFF */

/* __COLIBRI_LIB_LINUX_KERNEL_TYPES_H_ */
#endif
/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
