#!/bin/sh

. /etc/rc.d/init.d/functions

db_path=$C2T1FS_IO_TEST_DIR/db
stob_path=$C2T1FS_IO_TEST_DIR/stobs
end_point=$COLIBRI_SERVER_END_POINT
stob_domain=$STOB_DOMAIN

prog=$COLIBRI_CORE/colibri/colibri_setup
exec=$COLIBRI_CORE/colibri/.libs/lt-colibri_setup
args="-r -T "$stob_domain" -D "$db_path" -S "$stob_path" -e bulk-sunrpc:"$end_point" -s ioservice"


start() {
        exec $prog $args &
}

stop() {
        killproc $exec
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 2
esac
exit $?

