---
basic_tools_pkgs:
  - tmux
  - vim
  - emacs
  - pdsh
  # machine autodicovery by hostname
  - avahi
  - avahi-tools
  - nss-mdns
  - bind-utils
  # remote syslog
  - systemd-journal-gateway

avahi_service: avahi-daemon

redhat_vault_repo_versions:
  - C7.0.1406
  - C7.1.1503
  - C7.2.1511
  - C7.3.1611
  # TODO: enable when 7.5 forks off
  #- C7.4.1708
