nobase_mero_include_HEADERS += mgmt/mgmt.h \
			       mgmt/mgmt_addb.h \
			       mgmt/mgmt_fops.h \
			       mgmt/mgmt_pvt.h \
			       mgmt/svc/mgmt_svc_pvt.h

XC_FILES   += mgmt/mgmt_fops_xc.h

mero_libmero_la_SOURCES  += mgmt/mgmt.c \
			    mgmt/mgmt_conf.c \
			    mgmt/mgmt_fops_xc.c

EXTRA_DIST += mgmt/svc/fop_ss.c \
	      mgmt/svc/fop_ssr.c \
	      mgmt/svc/mgmt_svc.c

CLEANFILES += mgmt/mgmt_fops_xc.c \
	      mgmt/mgmt_fops_xc.h \
	      mgmt/mgmt_fops.gccxml
