#
# Very simple python script that can verify that the stream generated by
# m0addbdump -y is a valid stream of YAML documents.
#

import sys
import yaml

if len(sys.argv) == 1:
    stream = sys.stdin
else:
    stream = open(sys.argv[1], 'r')

for r in yaml.safe_load_all(stream):
    print r
