/* -*- C -*- */
#ifndef __COLIBRI_RPC_TYPES_H__

#define __COLIBRI_RPC_TYPES_H__

#include <lib/cdefs.h>

/**
 @page rpc-types type definitions used in rpc library
 */

/**
 unique session identifier
 - generated by server and and should be don't used until we will be know that
   client will newer connected.
 */
struct c2_session_id {
	uint64_t id;
};

/**
 compare sessions identifier

 @param s1 first session identifier
 @param s2 second session identifier

 @retval true if session identifiers is same
 @retval false if session identifiers is different
*/
bool c2_session_is_same(const struct c2_session_id *s1,
			const struct c2_session_id *s2);


/**
 type to define slot id
*/
typedef uint32_t c2_slot_t;


/**
 type to define sequence in a slot
 */
typedef uint64_t c2_seq_t;

#endif
