/* -*- C -*- */
/*
 * COPYRIGHT 2011 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Subhash Arya <subhash_arya@xyratex.com>,
 * Original creation date: 11/4/2011
 */
/**
   @addtogroup rpc_layer_core

   This file is a centralized (temporary) location for opcodes.
   An opcode is an rpc item type attribute which uniquely identifies an rpc
   item type.
   @see rpc/rpccore.h
   @see rpc/rpc_base.h

   @{
 */

enum {
	/** Network rpc opcodes */
	C2_NET_TEST_OPCODE = 1,

	/** ADDB rpc opcodes */
	C2_ADDB_RECORD_REQUEST_OPCODE,
	C2_ADDB_REPLY_OPCODE,

	/** Bulk emulation rpc opcodes */
	C2_BULK_SUNRPC_MSG_OPCODE,
	C2_BULK_SUNRPC_GET_OPCODE,
	C2_BULK_SUNRPC_PUT_OPCODE,
	C2_BULK_SUNRPC_MSG_REPLY_OPCODE,
	C2_BULK_SUNRPC_GET_REPLY_OPCODE,
	C2_BULK_SUNRPC_PUT_REPLY_OPCODE,

	/** Fol rpc opcodes */
	C2_FOL_ANCHOR_TYPE_OPCODE,
	C2_FOL_UT_OPCODE,

	/** Fop iterator rpc opcodes */
	C2_FOP_ITERATOR_TEST_OPCODE,

	/** I/O service rpc opcodes */
	C2_IOSERVICE_READV_OPCODE,
	C2_IOSERVICE_WRITEV_OPCODE,
	C2_IOSERVICE_READV_REP_OPCODE,
	C2_IOSERVICE_WRITEV_REP_OPCODE,

	/** Request handler rpc opcodes */
	C2_REQH_ERROR_REPLY_OPCODE,
	C2_REQH_UT_CREATE_REQ_OPCODE,
	C2_REQH_UT_WRITE_REQ_OPCODE,
	C2_REQH_UT_READ_REQ_OPCODE,
	C2_REQH_UT_CREATE_REPLY_OPCODE,
	C2_REQH_UT_WRITE_REPLY_OPCODE,
	C2_REQH_UT_READ_REPLY_OPCODE,

	/** RPC module opcodes */
	C2_RPC_PING_OPCODE,
	C2_RPC_PING_REPLY_OPCODE,
	C2_RPC_CONN_ESTABLISH_OPCODE,
        C2_RPC_CONN_TERMINATE_OPCODE,
        C2_RPC_SESSION_ESTABLISH_OPCODE,
        C2_RPC_SESSION_TERMINATE_OPCODE,
        C2_RPC_CONN_ESTABLISH_REP_OPCODE,
        C2_RPC_CONN_TERMINATE_REP_OPCODE,
        C2_RPC_SESSION_ESTABLISH_REP_OPCODE,
        C2_RPC_SESSION_TERMINATE_REP_OPCODE,
        C2_RPC_NOOP_OPCODE,
	C2_RPC_ONWIRE_UT_OPCODE,

	/** Stob rpc opcodes */
	C2_STOB_UT_WRITE_OPCODE,
	C2_STOB_UT_READ_OPCODE,
	C2_STOB_UT_CREATE_OPCODE,
	C2_STOB_UT_QUIT_OPCODE,
	C2_STOB_UT_WRITE_REPLY_OPCODE,
	C2_STOB_UT_READ_REPLY_OPCODE,
	C2_STOB_UT_CREATE_REPLY_OPCODE,

	/** Xcode rpc opcodes */
	C2_XCODE_UT_OPCODE,
};
/** @} endgroup rpc_layer_core */

/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */

