/* -*- C -*- */
#ifndef _RPC_TYPES_H_

#define _RPC_TYPES_H_

#include "lib/cdefs.h"

/**
 @page rpc-types type definitions used in rpc library
 */

/**
 unique session identifier
 - generated by server and and should be don't used until we will be know that
   client will newer connected.
 */
struct c2_session_id {
	uint64_t id;
};

/**
 compare sessions identifier

 @param s1 first session identifier
 @param s2 second session identifier

 @retval true if session identifiers is same
 @retval false if session identifiers is different
*/
bool c2_session_is_same(struct session_id const *s1, struct session_id const *s2);


/**
 type to define sequence in a slot
 */
typedef uint32_t c2_seq_t;

#endif
