nobase_colibri_include_HEADERS += fid/fid.h fid/fid_xc.h
colibri_libcolibri_la_SOURCES  += fid/fid.c fid/fid_xc.c

XC_FILES   += fid/fid_xc.h fid/fid_xc.h

CLEANFILES += fid/fid_xc.h \
              fid/fid_xc.c \
              fid/fid.gccxml
