---
# allow to override hosts to which this playbook applies in command line
# using '-e override_hosts=HOSTS' option
- hosts:  '{{ override_hosts | default("cmu") }}'
  become: yes  # run all commands as root
  roles:
    - ssh-master
    - base-os
    - journald-master
    - lustre-client
    - mero-build
    - mero-runtime
    - halon-build
    - halon-runtime
    - { role: xperior-runtime, tags: xperior }
