#
# Mero runtime
#
---
- name: dynamically load variables depending on the OS type
  include_vars: '{{ item  }}'
  with_first_found: '{{ ansible_os_family }}.yml'

- name: install Mero run-time dependencies
  package:
    state: present
    name:  '{{ mero_runtime_deps_pkgs }}'

- name: get current kernel version
  command:  uname -r
  register: kernel_version
  changed_when: false
  tags: debuginfo

- name: install kernel-debuginfo package
  package:
    state: present
    name:  kernel-debuginfo-{{ kernel_version.stdout }}
  tags:
    - debuginfo

- name: create Mero system group
  group:
    name: mero
    system: yes
