EXTRA_DIST += c2t1fs/linux_kernel/c2loop.c \
              c2t1fs/linux_kernel/c2t1fs.c \
              c2t1fs/linux_kernel/c2t1fs.h \
              c2t1fs/linux_kernel/dir.c \
              c2t1fs/linux_kernel/file.c \
              c2t1fs/linux_kernel/inode.c \
              c2t1fs/linux_kernel/super.c \
	      c2t1fs/linux_kernel/file_internal.h
