#!/bin/sh
#
# Usage: rmt [-k] <WORKDIR> <COMMAND>
#
#   -k    keep going on failure.

if [ $1 = "-k" ]; then KEEP_GOING=true; shift; else KEEP_GOING=false; fi
dir=$1
shift
echo "cd /vagrant/$dir; $@" | ssh -TF scripts/circleci/ssh.config aws
rc=$?
if [ $rc != 0 ] && [ $KEEP_GOING != true ]
then
    vagrant destroy -f
    rm scripts/circleci/ssh.config
fi
exit $rc
