nobase_mero_include_HEADERS += \
                               graph/graph_xc.h \
                               graph/graph.h

mero_libmero_la_SOURCES  += \
                            graph/graph.c \
                            graph/graph_xc.c

XC_FILES   += graph/graph_xc.h
