#
# Ansible
#
---
- name: install Ansible on Debian based distro
  when: ansible_os_family == 'Debian'
  block:
    - name: install Ansible repo dependencies
      apt: name=software-properties-common

    - name: install Ansible PPA repo
      apt_repository:
        repo: ppa:ansible/ansible

    - name: install Ansible
      apt: name=ansible update_cache=yes
  tags: ansible
