#!/bin/bash


# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders

# service local variables
user_config=/etc/sysconfig/mero
service_funcs=/usr/libexec/mero/mero-service.functions


start()
{
    source $service_funcs

    [ -r $user_config ] && source $user_config

    MERO_LNET_NID=$(m0_get_lnet_nid)

    services=$(m0_get_services)
    mds_ep=${MERO_MDS_EP:-$(m0_get_mds_ep)}
    confd_ep=${MERO_CONFD_EP:-$(m0_get_confd_ep)}
    ios_eps=${MERO_IOS_EPS:-$(m0_get_ios_eps)}

    case $services in
        *singlenode*)
            [ "$services" != "confd singlenode" ] && \
                m0_exit "Invalid services list: 'singlenode' can't be used" \
                        " with other services"
            ;;
        mds)
            [ -z "$ios_eps" ] && \
                m0_exit "Error: IOS endpoints should be set either in" \
                        " /etc/sysconfig/mero or in /etc/mero/genders," \
                        " in order to start only 'mds' service w/o 'ios'"
            ;;
        *ios*)
            [ -z "$mds_ep" ] && \
                m0_exit "Error: MDS endpoint should be set in either" \
                        " /etc/sysconfig/mero or in /etc/mero/genders," \
                        " in order to start only 'ios*' services w/o 'mds'"
            ;;
    esac

    # set positional parameters to IOS endpoints
    eval set -- "$ios_eps"

    for s in $services; do
        case $s in
            mds|singlenode) ep=$mds_ep ;;
            confd) ep=$confd_ep ;;
            ios*) ep=$1; shift ;;
        esac
        service_dir=$(m0_get_m0d_data_dir_for $s)
        [ ! -d "$service_dir" ] && mkdir -p "$service_dir"
        echo "EP=$ep" > $service_dir/env.conf
        systemctl start mero-server@${s}.service
    done
}

stop()
{
    source $service_funcs

    [ -r $user_config ] && source $user_config

    for s in $(m0_get_running_servers); do
        systemctl stop mero-server@${s}.service
    done
}


case $1 in
    start)  start ;;
    stop)   stop ;;
esac
