#!/bin/bash


# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders

# service local variables
user_config=/etc/sysconfig/mero
service_funcs=/usr/libexec/mero/mero-service.functions


start()
{
    source $service_funcs

    [ -r $user_config ] && source $user_config

    MERO_LNET_NID=$(m0_get_lnet_nid)

    services=$(m0_get_services)

    for s in $services; do
        case $s in
            rms*|mds*|ios*) t='@' ;;
            confd|ha) t='-'  ;;
        esac

        service_dir=$(m0_get_m0d_data_dir_for $s)
        [ ! -d "$service_dir" ] && mkdir -p "$service_dir"

        systemctl start mero-server${t}${s}.service
    done
}

stop()
{
    source $service_funcs

    [ -r $user_config ] && source $user_config

    for s in $(m0_get_running_servers | grep -v confd); do
        systemctl stop mero-server@${s}.service
    done

    if [[ -n $(m0_get_running_servers | grep confd) ]] ; then
        systemctl stop mero-server-confd.service
    fi
}


case $1 in
    start)  start ;;
    stop)   stop ;;
esac
