#!/bin/bash


# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders
MERO_M0D_OPTS=''

# service local variables
user_config=/etc/sysconfig/mero
service_funcs=/usr/libexec/mero/mero-service.functions


m0_server()
{
    local service=$1
    local cmd=${2:-m0d}
    local cmd_opts="$3"

    source $service_funcs

    [[ -n $service ]] || m0_exit "usage: $PROG_NAME <SERVICE>"

    [ -r $user_config ] && source $user_config

    [ -n "$MERO_M0D_DEBUGGER" ] && export M0_DEBUGGER=$MERO_M0D_DEBUGGER

    local service_dir=$(m0_get_m0d_data_dir_for $service)
    if [ x$MERO_M0D_REMOVE_SERVICE_DIR = xtrue ] && [ -d "$service_dir" ] ; then
        rm -rf "$service_dir"
    fi
    [ ! -d "$service_dir" ] && mkdir -p "$service_dir"
    cd $service_dir

    local MERO_M0D_OPTS+=$(m0_get_core_params)
    local m0d_services='-s addb2'
    local stob_type='-T ad'
    local stob_opts

    case "$service" in
        mds*)  m0d_services+=' -s mdservice -s rmservice -s stats'
            ;;

        ios*)  stob_opts+=" -d /etc/mero/disks-$service.conf"
               m0d_services+=' -s ioservice -s sns_repair -s sns_rebalance'
            ;;

        confd) stob_type='-T linux'
               m0d_services+=' -s confd'
               MERO_M0D_OPTS+=' -c conf.xc'
            ;;

        ha)    stob_type='-T linux'
               unset m0d_services
            ;;

        singlenode)
               stob_opts+=" -d /etc/mero/disks-$service.conf"
               m0d_services+=' -s mdservice -s stats -s ioservice \
                               -s sns_repair -s sns_rebalance'
            ;;

        *) m0_exit "Failed to start unknown service '$service'," \
                   " available services are 'mds*' and 'ios*'"
            ;;
    esac

    local confd_ep=${MERO_CONFD_EP:-$(m0_get_global_ep_of confd)}
    local service_ep="lnet:$(m0_get_ep_of $service)"

    if [[ $service == confd ]]; then
        m0_build_local_conf > $service_dir/conf.xc
    else
        MERO_M0D_OPTS+=" -C $confd_ep"
    fi

    local binary=$(m0_path_to $cmd)

    # enable core dumps
    ulimit -c unlimited

    # show actual exec commands in log file
    set -x

    exec $binary -e $service_ep $stob_type $MERO_M0D_OPTS $m0d_services \
                    $stob_opts $MERO_M0D_EXTRA_OPTS $cmd_opts
}


m0_server "$@"
