#!/bin/bash


# constants
readonly PROG_NAME=$(basename $0)

# global variables, which can be overriden in /etc/sysconfig/mero
MERO_GENDERS_CONF=/etc/mero/genders
MERO_M0D_OPTS=""

# service local variables
user_config=/etc/sysconfig/mero
service_funcs=/usr/libexec/mero/mero-service.functions


m0_server()
{
    local service=$1

    source $service_funcs

    [[ -n $service ]] || m0_exit "usage: $PROG_NAME <SERVICE>"

    [ -r $user_config ] && source $user_config

    [ -n "$MERO_M0D_DEBUGGER" ] && export M0_DEBUGGER=$MERO_M0D_DEBUGGER

    service_dir=$(m0_get_m0d_data_dir_for $service)
    if [ x$MERO_M0D_REMOVE_SERVICE_DIR = xtrue ] && [ -d "$service_dir" ] ; then
        rm -rf "$service_dir"
    fi
    [ ! -d "$service_dir" ] && mkdir -p "$service_dir"
    cd $service_dir

    env_config=$service_dir/env.conf
    [ -r $env_config ] && source $env_config

    stob_type='-T ad'
    stob_opts='-D db -S stobs -A linuxstob:addb-stobs'

    params=$(m0_get_core_params $service_dir)
    case "$service" in
        mds)  stob_type='-T linux'
              m0d_services="-s mdservice -s stats $params"
            ;;

        ios*) stob_opts+=" -d /etc/mero/disks-$service.conf"
              m0d_services="-s ioservice -s sns_repair -s sns_rebalance $params"
            ;;

        confd) stob_type='-T linux'
               m0d_services="-s confd -c conf.xc $params"
            ;;

        singlenode)
              stob_opts+=" -d /etc/mero/disks-$service.conf"
              m0d_services="-s mdservice -s stats -s ioservice \
                            -s sns_repair -s sns_rebalance $params"
            ;;

        *) m0_exit "Failed to start unknown service '$service'," \
                   " available services are 'mds' and 'ios*'"
            ;;
    esac

    m0mkfs=$(m0_path_to m0mkfs)
    m0d=$(m0_path_to m0d)

    if [ $service != "confd" ]; then
        confd_ep=${MERO_CONFD_EP:-$(m0_get_confd_ep)}
        MERO_M0D_OPTS+=" -P $m0_prof_opt -C ${confd_ep#lnet:}"
    fi

    pool_width=$(m0_genders_value_of m0_pool_width)
    MERO_M0D_OPTS+=" -w $pool_width \
                     -m $(m0_genders_value_of m0_max_rpc_msg_size) \
                     -q $(m0_genders_value_of m0_min_rpc_recvq_len)"

    # show actual exec commands in log file
    set -x

    exec $m0d $MERO_M0D_OPTS $stob_type $stob_opts $m0d_services \
              -e $EP $MERO_M0D_EXTRA_OPTS
}


m0_server $1
