version: 2

jobs:
  build:
    working_directory: ~/mero
    docker:
      - image: seagate/mero-devel:7.4
        auth:
          username: seagateci
          password: $SSG_DOCKERHUB_PASSWD
    steps:
      - checkout

      - run:
          name: Checking-out git submodules
          command: |
              git submodule sync --recursive
              git submodule update --init --recursive

      - run:
          name: Mero revision
          command: |
              git describe
              git --no-pager log -1

      - run:
          name: Building Mero
          command: |
              ./autogen.sh
              ./configure --with-linux=/lib/modules/$(yum list installed kernel | tail -n1 | awk '{ print $2 }').x86_64/build
              make -j8

      - run:
          name: Building Mero rpms
          command: |
              make rpms kernel_src=/lib/modules/$(yum list installed kernel | tail -n1 | awk '{ print $2 }').x86_64/build

workflows:
  version: 2
  precommit:
    jobs:
      - build:
          context: ssg-auth
