ut_libmero_ut_la_SOURCES += \
    conf/ut/cache.c         \
    conf/ut/confc.c         \
    conf/ut/confc.h         \
    conf/ut/common.h        \
    conf/ut/common.c        \
    conf/ut/diter.c         \
    conf/ut/db.c            \
    conf/ut/load.c          \
    conf/ut/rpc_helpers.c   \
    conf/ut/rpc_helpers.h   \
    conf/ut/rconfc.c        \
    conf/ut/validation.c

CONFXC_FILES += \
    conf/ut/duplicated-ids.xc \
    conf/ut/t_path.xc
