ut_libmero_ut_la_SOURCES += \
    conf/ut/confc.c            \
    conf/ut/main.c             \
    conf/ut/network.c          \
    conf/ut/obj.c              \
    conf/ut/reg.c              \
    conf/ut/rpc_helpers.c      \
    conf/ut/rpc_helpers.h      \
    conf/ut/xread.c

ut_libmero_ut_la_CPPFLAGS += \
    -DMERO_CONFX_OBJ_CFG=$(abs_top_builddir)/conf/ut/conf_xc.txt \
    -DMERO_CONFX_OBJ_CFG_XC=$(abs_top_builddir)/conf/ut/conf_xc.txt
