ut_libmero_ut_la_SOURCES += \
    conf/ut/cache.c         \
    conf/ut/confc.c         \
    conf/ut/confc.h         \
    conf/ut/common.h        \
    conf/ut/common.c        \
    conf/ut/dir_iter.c      \
    conf/ut/db.c            \
    conf/ut/rpc_helpers.c   \
    conf/ut/rpc_helpers.h

ut_libmero_ut_la_CPPFLAGS += -DM0_CONF_UT_STR_NR_OBJS=$(shell \
	grep -Em1 '^\[[0-9]+:' ut/conf-str.txt | \
	cut -d: -f1 | cut -d\[ -f2-)
