#
# NFS server tasks
#
---
- name: configure NFS server
  block:
    - name: collect user facts
      # initial Ansible facts are collected on behalf of 'root' user due to
      # 'become: yes' directive in the top-level playbook, we need to override
      # those with real ssh user info because we want to export user's home dir,
      # not /root
      become: no
      setup:
        filter: ansible_user_*

    - name: create mountpoint for nfs-client {{ ansible_user_dir }}/{{ cmu_nfs_mountpoint }}
      become: no
      file:
        path: '{{ ansible_user_dir }}/{{ cmu_nfs_mountpoint }}'
        state: directory

    - name: create NFS server exportfs config
      template:
        src: vagrant-home.exports.j2
        dest: /etc/exports.d/vagrant-home.exports

    - name: start nfs-server
      service: name=nfs-server state=started enabled=yes

    - name: export NFS dirs
      command: exportfs -rav
      changed_when: false
  tags: nfs-server
