mero_libmero_la_SOURCES  += addb/addbff/addb_xc.h \
                            addb/addbff/addb_xc.c

XC_FILES   += addb/addbff/addb_xc.h

EXTRA_DIST += addb/addbff/addb.h

CLEANFILES += addb/addbff/addb_xc.h \
              addb/addbff/addb_xc.c \
	      addb/addbff/addb.gccxml
