m0ut_objects += ut/cs_fop_foms.o \
                ut/cs_fop_foms_xc.o \
                ut/cs_service.o \
                ut/be.o \
                ut/threads.o \
                ut/ut.o \
                ut/linux_kernel/ut.o \
                ut/ut_rpc_machine.o \
