/* -*- C -*- */

/*
 * WARNING: this file is automatically generated
 * from fom_io.ff by fop2c. Do not edit.
 */

#include "lib/cdefs.h"
#include "fop/fop.h"
#include "fom_io_u.h"
#include "net/usunrpc/usunrpc.h"

static bool_t uxdr_c2_fom_fop_fid(XDR *xdrs, struct c2_fom_fop_fid *cfff)
{
	extern struct c2_fop_type_format c2_fom_fop_fid_tfmt;
	return c2_fop_type_uxdr(c2_fom_fop_fid_tfmt.ftf_out, xdrs, cfff);
}

struct c2_fop_memlayout c2_fom_fop_fid_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_fop_fid),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_fop_fid,
	.fm_child = {
		{ offsetof(struct c2_fom_fop_fid, f_seq) },
		{ offsetof(struct c2_fom_fop_fid, f_oid) },
	}
};

static bool_t uxdr_c2_fom_io_write(XDR *xdrs, struct c2_fom_io_write *cfiw)
{
	extern struct c2_fop_type_format c2_fom_io_write_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_write_tfmt.ftf_out, xdrs, cfiw);
}

struct c2_fop_memlayout c2_fom_io_write_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_write),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_write,
	.fm_child = {
		{ offsetof(struct c2_fom_io_write, fiw_object) },
		{ offsetof(struct c2_fom_io_write, fiw_value) },
	}
};

static bool_t uxdr_c2_fom_io_write_rep(XDR *xdrs, struct c2_fom_io_write_rep *cfiwr)
{
	extern struct c2_fop_type_format c2_fom_io_write_rep_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_write_rep_tfmt.ftf_out, xdrs, cfiwr);
}

struct c2_fop_memlayout c2_fom_io_write_rep_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_write_rep),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_write_rep,
	.fm_child = {
		{ offsetof(struct c2_fom_io_write_rep, fiwr_rc) },
		{ offsetof(struct c2_fom_io_write_rep, fiwr_count) },
	}
};

static bool_t uxdr_c2_fom_io_read(XDR *xdrs, struct c2_fom_io_read *cfir)
{
	extern struct c2_fop_type_format c2_fom_io_read_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_read_tfmt.ftf_out, xdrs, cfir);
}

struct c2_fop_memlayout c2_fom_io_read_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_read),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_read,
	.fm_child = {
		{ offsetof(struct c2_fom_io_read, fir_object) },
	}
};

static bool_t uxdr_c2_fom_io_read_rep(XDR *xdrs, struct c2_fom_io_read_rep *cfirr)
{
	extern struct c2_fop_type_format c2_fom_io_read_rep_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_read_rep_tfmt.ftf_out, xdrs, cfirr);
}

struct c2_fop_memlayout c2_fom_io_read_rep_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_read_rep),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_read_rep,
	.fm_child = {
		{ offsetof(struct c2_fom_io_read_rep, firr_rc) },
		{ offsetof(struct c2_fom_io_read_rep, firr_count) },
		{ offsetof(struct c2_fom_io_read_rep, firr_value) },
	}
};

static bool_t uxdr_c2_fom_io_create(XDR *xdrs, struct c2_fom_io_create *cfic)
{
	extern struct c2_fop_type_format c2_fom_io_create_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_create_tfmt.ftf_out, xdrs, cfic);
}

struct c2_fop_memlayout c2_fom_io_create_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_create),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_create,
	.fm_child = {
		{ offsetof(struct c2_fom_io_create, fic_object) },
	}
};

static bool_t uxdr_c2_fom_io_create_rep(XDR *xdrs, struct c2_fom_io_create_rep *cficr)
{
	extern struct c2_fop_type_format c2_fom_io_create_rep_tfmt;
	return c2_fop_type_uxdr(c2_fom_io_create_rep_tfmt.ftf_out, xdrs, cficr);
}

struct c2_fop_memlayout c2_fom_io_create_rep_memlayout = {
	.fm_sizeof = sizeof (struct c2_fom_io_create_rep),
	.fm_uxdr = (xdrproc_t)uxdr_c2_fom_io_create_rep,
	.fm_child = {
		{ offsetof(struct c2_fom_io_create_rep, ficr_rc) },
	}
};



/* 
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
