/* -*- C -*- */
#ifndef __COLIBRI_FOM_IO_KDEF_H__
#define __COLIBRI_FOM_IO_KDEF_H__

/*
 * WARNING: this file is automatically generated
 * from fom_io.ff by fop2c. Do not edit.
 */

#include "lib/cdefs.h"
#include "fop/fop.h"

struct c2_fom_fop_fid {
	uint64_t             f_seq;
	uint64_t             f_oid;
};

extern struct c2_fop_memlayout c2_fom_fop_fid_memlayout;

struct c2_fom_io_seg {
	uint64_t             f_offset;
	uint64_t             f_count;
};

extern struct c2_fop_memlayout c2_fom_io_seg_memlayout;

struct c2_fom_io_buf {
	uint32_t cib_count;
	uint32_t cfib_pgoff;
	struct page **cib_value;
};

extern struct c2_fop_memlayout c2_fom_io_buf_memlayout;

struct c2_fom_io_vec {
	uint32_t civ_count;
	struct c2_fom_io_seg *civ_seg;
};

extern struct c2_fop_memlayout c2_fom_io_vec_memlayout;

struct c2_fom_io_write {
	struct c2_fom_fop_fid siw_object;
	uint64_t             siw_offset;
	struct c2_fom_io_buf siw_buf;
};

extern struct c2_fop_memlayout c2_fom_io_write_memlayout;

struct c2_fom_io_write_rep {
	uint32_t             siwr_rc;
	uint32_t             siwr_count;
};

extern struct c2_fop_memlayout c2_fom_io_write_rep_memlayout;

struct c2_fom_io_read {
	struct c2_fom_fop_fid sir_object;
	struct c2_fom_io_seg sir_seg;
};

extern struct c2_fop_memlayout c2_fom_io_read_memlayout;

struct c2_fom_io_read_rep {
	uint32_t             sirr_rc;
	struct c2_fom_io_buf sirr_buf;
};

extern struct c2_fop_memlayout c2_fom_io_read_rep_memlayout;

struct c2_fom_io_create {
	struct c2_fom_fop_fid sic_object;
};

extern struct c2_fop_memlayout c2_fom_io_create_memlayout;

struct c2_fom_io_create_rep {
	uint32_t             sicr_rc;
};

extern struct c2_fop_memlayout c2_fom_io_create_rep_memlayout;

struct c2_fom_io_quit {
	uint32_t             siq_rc;
};

extern struct c2_fop_memlayout c2_fom_io_quit_memlayout;


/* __COLIBRI_FOM_IO_KDEF_H__ */
#endif

/* 
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
