/* -*- C -*- */

/*
 * WARNING: this file is automatically generated
 * from fom_io.ff by fop2c. Do not edit.
 */

#include "lib/cdefs.h"
#include "fop/fop.h"
#include "fom_io_u.h"
#include "net/usunrpc/usunrpc.h"

static bool_t uxdr_reqh_ut_fom_fop_fid(XDR *xdrs, struct reqh_ut_fom_fop_fid *rufff)
{
	extern struct c2_fop_type_format reqh_ut_fom_fop_fid_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_fop_fid_tfmt.ftf_out, xdrs, rufff);
}

struct c2_fop_memlayout reqh_ut_fom_fop_fid_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_fop_fid),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_fop_fid,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_fop_fid, f_seq) },
		{ offsetof(struct reqh_ut_fom_fop_fid, f_oid) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_write(XDR *xdrs, struct reqh_ut_fom_io_write *rufiw)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_write_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_write_tfmt.ftf_out, xdrs, rufiw);
}

struct c2_fop_memlayout reqh_ut_fom_io_write_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_write),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_write,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_write, fiw_object) },
		{ offsetof(struct reqh_ut_fom_io_write, fiw_value) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_write_rep(XDR *xdrs, struct reqh_ut_fom_io_write_rep *rufiwr)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_write_rep_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_write_rep_tfmt.ftf_out, xdrs, rufiwr);
}

struct c2_fop_memlayout reqh_ut_fom_io_write_rep_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_write_rep),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_write_rep,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_write_rep, fiwr_rc) },
		{ offsetof(struct reqh_ut_fom_io_write_rep, fiwr_count) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_read(XDR *xdrs, struct reqh_ut_fom_io_read *rufir)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_read_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_read_tfmt.ftf_out, xdrs, rufir);
}

struct c2_fop_memlayout reqh_ut_fom_io_read_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_read),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_read,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_read, fir_object) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_read_rep(XDR *xdrs, struct reqh_ut_fom_io_read_rep *rufirr)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_read_rep_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_read_rep_tfmt.ftf_out, xdrs, rufirr);
}

struct c2_fop_memlayout reqh_ut_fom_io_read_rep_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_read_rep),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_read_rep,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_read_rep, firr_rc) },
		{ offsetof(struct reqh_ut_fom_io_read_rep, firr_count) },
		{ offsetof(struct reqh_ut_fom_io_read_rep, firr_value) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_create(XDR *xdrs, struct reqh_ut_fom_io_create *rufic)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_create_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_create_tfmt.ftf_out, xdrs, rufic);
}

struct c2_fop_memlayout reqh_ut_fom_io_create_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_create),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_create,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_create, fic_object) },
	}
};

static bool_t uxdr_reqh_ut_fom_io_create_rep(XDR *xdrs, struct reqh_ut_fom_io_create_rep *ruficr)
{
	extern struct c2_fop_type_format reqh_ut_fom_io_create_rep_tfmt;
	return c2_fop_type_uxdr(reqh_ut_fom_io_create_rep_tfmt.ftf_out, xdrs, ruficr);
}

struct c2_fop_memlayout reqh_ut_fom_io_create_rep_memlayout = {
	.fm_sizeof = sizeof (struct reqh_ut_fom_io_create_rep),
	.fm_uxdr = (xdrproc_t)uxdr_reqh_ut_fom_io_create_rep,
	.fm_child = {
		{ offsetof(struct reqh_ut_fom_io_create_rep, ficr_rc) },
	}
};



/* 
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
