nobase_mero_include_HEADERS += mgmt/svc/ut/mgmt_svc_ut.h

ut_libmero_ut_la_SOURCES += mgmt/svc/ut/mgmt_svc_ut.c \
			    mgmt/svc/ut/mgmt_svc_ut_xc.c

XC_FILES   += mgmt/svc/ut/mgmt_svc_ut_xc.h

EXTRA_DIST += mgmt/svc/ut/fake_fom.c \
	      mgmt/svc/ut/fake_svc.c \
	      mgmt/svc/ut/mgmt_svc_setup.c
