#
# Journald slave tasks
#
---
- name: update systemd-journal-upload.service config
  replace:
    path:    /etc/systemd/journal-upload.conf
    regexp:  '# URL='
    replace: 'URL=http://cmu.local:19532'

- name: create directory for journald-upload state
  file:
    state: directory
    path:  /var/lib/systemd/journal-upload/
    owner: systemd-journal-upload
    group: systemd-journal-upload

- name: start systemd-journal-upload service
  service: name=systemd-journal-upload state=started enabled=yes
  tags: start-services
