m0mero_objects += stob/stob.o \
                  stob/ad_xc.o \
                  stob/ad_private_xc.o \
                  stob/stob_xc.o \
                  stob/cache.o \
                  stob/cache_xc.o \
                  stob/domain.o \
                  stob/domain_xc.o \
                  stob/io.o \
                  stob/ioq_error_xc.o \
                  stob/module.o \
                  stob/null.o \
                  stob/type.o
