#!/bin/bash
set -eu

### Removes comments and indentations, joins multiple lines into one.
confstr-desugar() {
    grep -vE '^\s*#'                |  # drop comment lines
        sed -E 's/^[[:space:]]+/ /' |
        tr -d \\n
    echo
}

cd "$M0_SRC_DIR"

set -o pipefail
DIFF="$(confstr-desugar <ut/conf-str.txt | tr ' ' \\n |
        diff -u --label 'm0confgen output' --label conf-str.txt \
            <(utils/m0confgen ut/conf-str.txt.in | tr ' ' \\n) -)" || {
    echo '**ERROR** m0confgen output and ut/conf-str.txt have' \
	 'semantic differences' >&2
    echo "$DIFF" >&2
    exit 1
}
