---
halon_build_deps_pkgs:
  - binutils-devel
  - libgenders-devel
  - git
  - gmp-devel
  - leveldb-devel
  - libyaml-devel
  - pcre-devel
  # latest version of stack is installed using official get-stack.sh scrip
  # so disabling it here
  #- stack
