---
- hosts:  all
  become: yes  # run all commands as root
  vars:
    reboot_delay_sec: 5
    reboot_wait_min:  1

  tasks:
    - name: configure 'EPEL' repository
      yum:  name=epel-release  state=present

    - name: configure 'Debuginfo' repository
      yum_repository:
        name:        debuginfo
        description: CentOS - Debuginfo
        baseurl:     http://debuginfo.centos.org/$releasever/$basearch/
        # debuginfo packages are not signed, need to disable signature verification
        gpgcheck: no

    - name: configure 'Lustre' repository
      yum_repository:
        name:        lustre-intel-{{ item.version }}
        file:        lustre-intel
        description: Intel - Lustre {{ item.version }}
        baseurl:     https://downloads.hpdd.intel.com/public/lustre/lustre-{{ item.version }}/el7/client/
        # disable signature verification
        gpgcheck: no
      with_items:
        - { version: 2.7.0 }
        - { version: 2.8.0 }
        - { version: 2.9.0 }

    - name: upgrade all packages to latest versions
      yum:  name=*  state=latest  update_cache=yes

    # reboot and reconnect. it's required because in the previous step
    # `yum upgrade` might have installed a new kernel
    - block:
      - name: reboot machine (in {{ reboot_delay_sec }} seconds)
        command: systemd-run --on-active={{ reboot_delay_sec }} systemctl reboot

      - name: wait for reboot to start and hopefully finish
        pause: minutes={{ reboot_wait_min }}

      - name: re-connect to rebooted machine before continuing
        command:  /bin/true
        register: online
        until:    online|success

    - name: install Mero build-time dependencies
      yum:
        state: present
        name:
          - asciidoc
          - autoconf
          - automake
          - binutils
          - binutils-devel
          - gcc
          - gcc-c++
          - gccxml
          - glibc-headers
          - kernel-devel
          - libaio
          - libaio-devel
          - libtool
          - libuuid-devel
          - libyaml
          - libyaml-devel
          - make
          - perl
          - perl-File-Find-Rule
          - perl-File-Slurp
          - perl-IO-All
          - perl-List-MoreUtils
          - perl-XML-LibXML
          - perl-autodie
          - python-devel
          - python-ply
          - rpm-build
          - systemd-devel

    - name: install Lustre sources
      yum:  name=lustre-client-dkms  state=present

    - name: build Lustre sources
      shell: cd /usr/src/lustre-* && {{ item }}
      with_items:
        - ./configure
        - make

    - name: install Mero run-time dependencies
      yum:
        state: present
        name:
          - attr
          - crash
          - expect
          - facter
          - gdb
          - genders
          - lustre-client
          - psmisc
          - ruby
          - time

