nobase_mero_include_HEADERS += fol/fol.h \
                                  fol/fol_private.h \
                                  fol/lsn.h \
                                  fol/fol_xc.h

mero_libmero_la_SOURCES  += fol/fol.c \
				fol/fol_xc.c

XC_FILES   += fol/fol_xc.h
