#!/bin/bash

readonly self=$(readlink -f $0)
readonly top_srcdir=${self%/*/*}

$top_srcdir/scripts/m0mount -alvvsL -n 1 -d 2 -k 1 -p 4 -o -m -q

# this msg is used by Jenkins as a test success criteria;
# it should appear on STDOUT
if [ $? -eq 0 ] ; then
    echo "m0mount: test status: SUCCESS"
fi
