#!/bin/bash

#
# Wrapper script for Jenkins test '3initscript-tests'
#

set -e
set -x

current_script_path=$(dirname $(readlink -f $0))
mero_src_dir=$(echo $current_script_path | sed -e 's#scripts/jenkins/tests$##')

sudo $mero_src_dir/st/m0t1fs -vv -r ~jenkins/rpmbuild/RPMS/x86_64/mero-?.?.?-*.rpm
