nobase_mero_include_HEADERS += \
			       sss/ss_fops.h \
			       sss/ss_svc.h \
			       sss/process_fops.h \
			       sss/process_foms.h

mero_libmero_la_SOURCES += sss/ss_fops.c    \
			   sss/ss_fops_xc.c \
			   sss/ss_svc.c \
			   sss/process_fops.c \
			   sss/process_fops_xc.c \
			   sss/process_foms.c

XC_FILES += sss/ss_fops_xc.h \
	    sss/process_fops_xc.h
