/* -*- C -*- */
/*
 * COPYRIGHT 2011 XYRATEX TECHNOLOGY LIMITED
 *
 * THIS DRAWING/DOCUMENT, ITS SPECIFICATIONS, AND THE DATA CONTAINED
 * HEREIN, ARE THE EXCLUSIVE PROPERTY OF XYRATEX TECHNOLOGY
 * LIMITED, ISSUED IN STRICT CONFIDENCE AND SHALL NOT, WITHOUT
 * THE PRIOR WRITTEN PERMISSION OF XYRATEX TECHNOLOGY LIMITED,
 * BE REPRODUCED, COPIED, OR DISCLOSED TO A THIRD PARTY, OR
 * USED FOR ANY PURPOSE WHATSOEVER, OR STORED IN A RETRIEVAL SYSTEM
 * EXCEPT AS ALLOWED BY THE TERMS OF XYRATEX LICENSES AND AGREEMENTS.
 *
 * YOU SHOULD HAVE RECEIVED A COPY OF XYRATEX'S LICENSE ALONG WITH
 * THIS RELEASE. IF NOT PLEASE CONTACT A XYRATEX REPRESENTATIVE
 * http://www.xyratex.com/contact
 *
 * Original author: Anatoliy Bilenko <Anatoliy_Bilenko@xyratex.com>
 * Original creation date: 08/06/2012
 */

#ifndef __COLIBRI_RDWR_TB_H__
#define __COLIBRI_RDWR_TB_H__
#include "rdwr_fop.h"

enum tb_request_type {
	RQ_WRITE_LOCK0,
	RQ_WRITE_LOCK1,
	RQ_READ_LOCK0, 
	RQ_READ_LOCK1,
	RQ_READ_LOCK2,
	RQ_READ_LOCK3,
	RQ_READ_LOCK4,
	RQ_READ_LOCK_WAKE,
	RQ_READ_LOCK5,
	RQ_READ_LOCK6,
	RQ_READ_LOCK7,
	RQ_READ_LOCK8,
	RQ_READ_LOCK9,
	RQ_READ_LOCK10,
	RQ_READ_LOCK11,
	RQ_READ_LOCK12,
	RQ_READ_LOCK13,
	RQ_READ_LOCK14,
	RQ_READ_LOCK15,
	RQ_READ_LOCK16,
	RQ_WRITE_LOCK_AFTER_READ,
	RQ_READ_LOCK_LAST,
	RQ_NR,
};

enum request_phase {
	PH_REQ_LOCK = C2_FOPH_NR + 1,
	PH_GOT_LOCK
};

enum {
	CLIENT_COB_DOM_ID	= 16,
	SESSION_SLOTS		= RQ_NR,
	MAX_RPCS_IN_FLIGHT	= RQ_NR,
	CONNECT_TIMEOUT		= 5,
};

void c2_rdwr_send_fop(struct c2_rpc_session *session);

#endif /* __COLIBRI_RDWR_TB_H__ */

/*
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
