m0mero_objects += clovis/clovis.o \
		  clovis/clovis_init.o \
		  clovis/cob.o \
		  clovis/clovis_obj.o \
		  clovis/idx_mock.o \
		  clovis/idx_cass.o \
		  clovis/idx_kvs.o \
		  clovis/clovis_idx.o \
		  clovis/io_pargrp.o \
		  clovis/io_req_fop.o \
		  clovis/io_req.o \
		  clovis/io_nw_xfer.o \
		  clovis/clovis_io.o \
		  clovis/clovis_osync.o \
		  clovis/clovis_realm.o \
		  clovis/utils.o
