EXTRA_DIST += build_kernel_modules/dummy_init_fini.c \
              build_kernel_modules/dummy_init_fini.h \
              build_kernel_modules/Lustre.symvers \
              build_kernel_modules/lustre_config.h \
              build_kernel_modules/main.c

