nobase_colibri_include_HEADERS += colibri/init.h \
                                  colibri/colibri_setup.h \
                                  colibri/magic.h

colibri_libcolibri_la_SOURCES  += colibri/init.c \
                                  colibri/colibri_setup.c

colibri_colibri_setup_SOURCES   = colibri/cs_main.c \
                                  colibri/cs_internal.h

EXTRA_DIST += colibri/devices.sh \
              colibri/DS-Reqh.gif \
              colibri/colibri-pub.api
