import os

Import('env')

srcdir = env['SRCDIR']
db4dir = env['DB4DIR']
dist = db4dir + "/dist"
build = srcdir + "/" + env['BUILDDIR']

cmd = 'cd %s; awk -f gen_rec.awk -v source_file=%s/src/fol/colibri_fol.c \
-v header_file=%s/src/fol/colibri_fol.h -v print_file=%s/src/fol/colibri_fol_print.c \
-v template_file=%s/src/fol/colibri_fol_template.0.c < %s/src/fol/colibri_fol.src' % (dist, build, build, build, build, srcdir)

gen_builder = Builder(action = cmd)
env.Append(BUILDERS = { "Gen" : gen_builder })

env.Append(LIBS=['db'])
gen = env.Gen('colibri_fol.src')
fol = env.StaticLibrary('fol', ['colibri_fol.c', 'colibri_fol_print.c', 'colibri_fol_template.c'])
Depends(fol, gen)