# This script parses index.html file generated by lcov and
# generates simple tabular data, which can be imported in
# some spreadsheet

if [ $# -ne 1 ]
then
	echo "usage: process_lcov index.html"
	exit 1
fi

printf "Module line_cov%% lines_hit lines_total function_cov%% functions_hit " 
printf "functions_total branch_cov%% branches_hit branches_total\n"

# read file | find interesting lines | remove all HTML tags | \
#     remove all "&nbsp;" | remove all leading spaces | remove all "/ " \
#     convert from one datum per line to tabular format | \
#     squeeze consecutive spaces

cat $1 | egrep "coverFile|coverPer|coverNum" | sed 's/<[/]*[^>]*>//g' | \
 sed 's/&nbsp;//g;' | sed 's/^[ \t]*//' |sed 's/\/ //g' | \
 awk '/[a-zA-Z]/  { printf "\n"} {printf "%s\t", $0} END { printf "\n"}' |\
 tr -s " "

