net_test_user_space_ntc_SOURCES  = net/test/user_space/common_u.c \
                                   net/test/user_space/common_u.h \
                                   net/test/user_space/console_u.c

net_test_user_space_ntn_SOURCES  = net/test/user_space/common_u.c \
                                   net/test/user_space/common_u.h \
                                   net/test/user_space/node_u.c
