#!/bin/bash

# This script reports any public funcnition, which is present in
# libcolibri-altogether.so, but not listed in colibri-pub.api file. Only
# functions, started which "c2_" prefix or which contain "tlist" in their names,
# are reported.


#
# Global vars
#

PROG_NAME=$(basename $0)

pub_api='colibri/colibri-pub.api'
libcolibri='colibri/.libs/libcolibri-altogether.so'


#
# Usage
#

help() {
    [ $1 -eq 0 ] && usage || usage >&2
    exit $1
}

usage() {
    cat <<EOF
Usage: $PROG_NAME [-h|--help] [-a|--api colibri-pub.api] [-l|--libcolibri libcolibri.so]

    -a|--api            A text file with the list of names of public colibri
                        functions. By default it's "$pub_api".

    -l|--libcolibri     libcolibri.so library binary, by default it's
                        "$libcolibri".

    -h|--help           Print this help screen.
EOF
}


#
# Parse CLI options
#

# Note that we use `"$@"' to let each command-line parameter expand to a
# separate word. The quotes around `$@' are essential!
# We need TEMP as the `eval set --' would nuke the return value of getopt.
TEMP=$(getopt -o ha:l: --long help,api:,libcolibri: -n "$PROG_NAME" -- "$@")

if [ $? != 0 ] ; then exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help) help 0 ;;
        -a|--api) pub_api=$2; shift 2 ;;
        -l|--libcolibri) libcolibri=$2; shift 2 ;;
        --) shift ; break ;;
        *) echo "getopt: internal error..." ; exit 1 ;;
    esac
done


#
# Main
#

if ! test -e "$libcolibri"; then
    # do nothing if libcolibri-altogether.so doesn't exist
    exit 0
fi

echo -n "Checking colibri public API...   "

# exit immediately if one the commands exits with a non-zero status
set -e

func_list=$(mktemp)

nm "$libcolibri" | awk '$2 == "T" && $3 ~ /^c2_.*|tlist/ {print $3}' | sort > $func_list

# if files are not equal
if ! diff -q $pub_api $func_list &> /dev/null; then
    echo "FAIL"
    echo "WARNING: Did you forget to add the following public functions"
    echo "         to the '$pub_api' list or to add C2_INTERNAL prefix to them?"
    echo ""
    diff -u $pub_api $func_list | grep -E '^[-+]\w'
else
    echo "OK"
fi

rm $func_list

exit 0
