#!/bin/bash

# This script reports any public funcnition, which is present in
# libmero-altogether.so, but not listed in mero-pub.api file. Only
# functions, started which "m0_" prefix or which contain "tlist" in their names,
# are reported.


#
# Global vars
#

PROG_NAME=$(basename $0)

pub_api='mero/mero-pub.api'
libmero='mero/.libs/libmero-altogether.so'


#
# Usage
#

help() {
    [ $1 -eq 0 ] && usage || usage >&2
    exit $1
}

usage() {
    cat <<EOF
Usage: $PROG_NAME [-h|--help] [-a|--api mero-pub.api] [-l|--libmero libmero.so]

    -a|--api            A text file with the list of names of public mero
                        functions. By default it's "$pub_api".

    -l|--libmero     libmero.so library binary, by default it's
                        "$libmero".

    -h|--help           Print this help screen.
EOF
}


#
# Parse CLI options
#

# Note that we use `"$@"' to let each command-line parameter expand to a
# separate word. The quotes around `$@' are essential!
# We need TEMP as the `eval set --' would nuke the return value of getopt.
TEMP=$(getopt -o ha:l: --long help,api:,libmero: -n "$PROG_NAME" -- "$@")

if [ $? != 0 ] ; then exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help) help 0 ;;
        -a|--api) pub_api=$2; shift 2 ;;
        -l|--libmero) libmero=$2; shift 2 ;;
        --) shift ; break ;;
        *) echo "getopt: internal error..." ; exit 1 ;;
    esac
done


#
# Main
#

if ! test -e "$libmero"; then
    # do nothing if libmero-altogether.so doesn't exist
    exit 0
fi

echo -n "Checking mero public API...   "

# exit immediately if one the commands exits with a non-zero status
set -e

func_list=$(mktemp)

# to have identical sorting order, we need to sort file's content using the same
# locale

nm "$libmero" | awk '$2 == "T" && $3 ~ /^m0_.*|tlist/ {print $3}' | LC_ALL=C sort > $func_list

pub_api_sorted=$(mktemp)
LC_ALL=C sort $pub_api > $pub_api_sorted

# if files are not equal
if ! diff -q $pub_api_sorted $func_list &> /dev/null; then
    echo "FAIL"
    echo "WARNING: Did you forget to add the following public functions"
    echo "         to the '$pub_api' list or to add M0_INTERNAL prefix to them?"
    echo ""
    diff -u $pub_api_sorted $func_list | grep -E '^[-+]\w'
else
    echo "OK"
fi

rm $func_list $pub_api_sorted

exit 0
