#!/bin/sh
set -e

### --------------------------------------------------------------------
### Mero helper script
###
### Installation:
###     ln -s /path/to/mero/core/scripts/m0 ~/bin/m0
###
### Type `m0 help' for usage.
### --------------------------------------------------------------------

RUNDIR=$HOME/XXX  # CAUTION! This directory will be removed by superuser.
PROG="${0##*/}"
SRC="$(readlink -f $0)"
SRC="${SRC%/*/*}"

SUDO='sudo -E'

clean() {
    cd "$SRC"
    make distclean $MAKE_OPTS || true
    [ "$1" = '-f' ] && git clean -fdx || true
}

build() {
    autoreconf -ifs
    ./configure $CONFIGURE_OPTS
    make $MAKE_OPTS
}

_reset() {
    $SUDO rm -rf "$RUNDIR"  # Ouch!
    mkdir "$RUNDIR"
    cd "$RUNDIR"
}

run_ut()  { _reset; $SUDO "$SRC/utils/ut.sh" "$@"; }

run_kut() {
    _reset
    echo 'Running kernel UT (this may take a while) ...'
    $SUDO "$SRC/utils/linux_kernel/ut.sh"
}

run_st() {
    _reset
    $SUDO "$SRC/m0t1fs/linux_kernel/st/st"
    $SUDO "$SRC/m0t1fs/linux_kernel/st/m0t1fs_test.sh"
}

dist_check() {
    local DIST=mero-0.1.0

    cd "$SRC"
    [ -f Makefile ] || {
	echo "You need to \`$PROG rebuild' first." >&2
	exit 1
    }
    make dist $MAKE_OPTS

    cd ..
    ## Don't let NFS preserve files' ownership.
    tar --no-same-owner -xzf "$SRC/$DIST.tar.gz"
    trap "rm -r '$SRC/../$DIST'" 0

    cd $DIST
    build
    cd -

    [ "$1" = '-a' ] || rm "$SRC/$DIST.tar.gz"
}

help() {
    [ $1 -eq 0 ] && _usage || _usage >&2
    exit $1
}

_usage() {
    cat <<EOF
Usage: $PROG COMMAND [OPTION]...

Commands:
    rebuild             Clean and build the whole Mero anew.

    run-ut [OPTION]...  Run user-space unit tests.
                        OPTIONs are passed to utils/ut.sh.

    run-kut             Run kernel unit tests.

    run-st              Run system tests.

    run-all             Run unit and system tests.

    dist-check [-a]     Create and validate Mero distribution archive.
                        The resulting archive file will be deleted,
                        unless '-a' option is used.

    check-everything  = (rebuild + dist-check + run-all) * 2
                        Please run this command before landing.
                        .
                        '* 2' means that the command is being run two
                        times; the second time with './configure
                        --disable-m0-asserts'.

    clean [-f]          Call 'make distclean' in M0 sources directory.
                        '-f' will also remove untracked files and
                        directories (i.e. those not added to the git
                        repository).
                        *CAUTION*: You do not want to use '-f' option if
                        there are any untracked files you care about.

    help    Show this help and exit.

Environment variables:
    CONFIGURE_OPTS      Extra options for './configure' command.
    MAKE_OPTS           Extra options for 'make' command.

M0 sources: $SRC
UT output:  $RUNDIR
EOF
}

case "$1" in
    rebuild) clean; build;;
    run-ut)  shift; run_ut "$@";;
    run-kut) run_kut;;
    run-st)  run_st;;
    run-all)
        shift; run_ut "$@"
        run_kut
        run_st;;
    dist-check) shift; dist_check "$@";;
    check-everything)
        while true; do
            clean
            build
            dist_check
            run_ut
            run_kut
            run_st
	    if echo $CONFIGURE_OPTS | grep -qe '--disable-m0-asserts'; then
		break
	    else
		CONFIGURE_OPTS="$CONFIGURE_OPTS --disable-m0-asserts"
	    fi
        done;;
    clean) shift; clean "$@";;
    help) help 0;;
    *)    help 1;;
esac
