#!/bin/bash

echo 'Resulting ELF image sizes:'

size mero/.libs/libmero{,-altogether}.so \
     build_kernel_modules/m0mero.ko \
     2>/dev/null \
| sed -r -e 's/dec/total/' \
         -e 's#mero/.libs/|build_kernel_modules/##' \
| cut -f5 --complement \
| column -t
