/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _T_H_RPCGEN
#define _T_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef uint64_t c2_bindex_t;

struct c2_fid {
	uint64_t f_seq;
	uint64_t f_oid;
};
typedef struct c2_fid c2_fid;

struct iovec {
	struct {
		u_int iv_buf_len;
		uint8_t *iv_buf_val;
	} iv_buf;
};
typedef struct iovec iovec;

struct fop_write {
	struct c2_fid wr_fid;
	c2_bindex_t wr_offset;
	iovec wr_iovec;
};
typedef struct fop_write fop_write;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_c2_bindex_t (XDR *, c2_bindex_t*);
extern  bool_t xdr_c2_fid (XDR *, c2_fid*);
extern  bool_t xdr_iovec (XDR *, iovec*);
extern  bool_t xdr_fop_write (XDR *, fop_write*);

#else /* K&R C */
extern bool_t xdr_c2_bindex_t ();
extern bool_t xdr_c2_fid ();
extern bool_t xdr_iovec ();
extern bool_t xdr_fop_write ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_T_H_RPCGEN */
