/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "t.h"

bool_t
xdr_c2_bindex_t (XDR *xdrs, c2_bindex_t *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_c2_fid (XDR *xdrs, c2_fid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->f_seq))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->f_oid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_iovec (XDR *xdrs, iovec *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->iv_buf.iv_buf_val, (u_int *) &objp->iv_buf.iv_buf_len, ~0,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fop_write (XDR *xdrs, fop_write *objp)
{
	register int32_t *buf;

	 if (!xdr_c2_fid (xdrs, &objp->wr_fid))
		 return FALSE;
	 if (!xdr_c2_bindex_t (xdrs, &objp->wr_offset))
		 return FALSE;
	 if (!xdr_iovec (xdrs, &objp->wr_iovec))
		 return FALSE;
	return TRUE;
}
