ut_libmero_ut_la_SOURCES += rm/ut/rings.c \
                            rm/ut/rmapi.c \
                            rm/ut/lcredits.c \
                            rm/ut/rcredits.c \
                            rm/ut/rm_foms.c \
                            rm/ut/rm_fops.c \
                            rm/ut/rmut.c \
                            rm/ut/rm_service.c \
                            rm/ut/group.c

EXTRA_DIST += rm/ut/rings.h rm/ut/rings.c rm/ut/rmut.h
