#!/bin/bash

#
# Main script for mero-build Jenkins job
#

# auto export all variables
set -a

# exit with error code on any command failure (including pipes)
set -e
set -o pipefail


WORKSPASE=$(pwd)
ARTIFACTS=$WORKSPASE/artifacts

if [[ -d $ARTIFACTS ]] ; then
    rm -f $ARTIFACTS/*
else
    mkdir $ARTIFACTS
fi

# for backward compatibility with old Jenkins environment we need to `cd` into
# 'workdir/src' directory if it exists, that is where old Jenkins jobs stored
# mero sources
src_dir=workdir/src
[[ ! -d $src_dir ]] || cd $src_dir

sudo git clean -dfx
sudo git submodule foreach git clean -dfx
git submodule update

./autogen.sh |& tee $ARTIFACTS/configure.log
./configure --enable-detailed-backtrace |& tee -a $ARTIFACTS/configure.log

if [[ $1 = docs ]] ; then
make -j doc |& tee $ARTIFACTS/make.log
else
[[ -d $HOME/rpmbuild ]] && rm -rf $HOME/rpmbuild/*
make -j |& tee $ARTIFACTS/make.log
make -j rpms |& tee $ARTIFACTS/rpm.log
cp -av $HOME/rpmbuild/RPMS/x86_64/mero*.rpm $ARTIFACTS/
cp -av $HOME/rpmbuild/SRPMS/mero*.rpm $ARTIFACTS/
fi
