ut_libmero_ut_la_SOURCES += rpc/ut/rpclib_ut.c \
                               rpc/ut/service.c \
                               rpc/ut/formation2.c \
                               rpc/ut/conn.c \
                               rpc/ut/rpc_machine.c \
                               rpc/ut/session.c \
                               rpc/ut/item.c \
			       rpc/ut/packet.c

EXTRA_DIST                  += rpc/ut/clnt_srv_ctx.c
