nobase_mero_include_HEADERS += stats/stats_srv.h     \
                               stats/stats_fops.h    \
			       stats/stats_addb.h    \
			       stats/stats_api.h     \
                               stats/stats_fops_xc.h

mero_libmero_la_SOURCES  += stats/stats_srv.c        \
			    stats/stats_fops.c       \
			    stats/stats_api.c        \
			    stats/stats_fops_xc.c

XC_FILES   += stats/stats_fops_xc.h
