m0mero_objects += \
                  dtm/catalogue.o \
                  dtm/domain.o \
                  dtm/dtm.o \
                  dtm/dtm_update_xc.o \
                  dtm/dtx.o \
                  dtm/factory.o \
                  dtm/history.o \
                  dtm/ltx.o \
                  dtm/nucleus.o \
                  dtm/object.o \
                  dtm/operation.o \
                  dtm/update.o \
                  dtm/verno.o \
                  dtm/verno_xc.o
