nobase_mero_include_HEADERS += dtm/dtm.h \
                                  dtm/verno.h \
                                  dtm/verno_xc.h

mero_libmero_la_SOURCES  += dtm/dtm.c \
                                  dtm/verno.c \
                                  dtm/verno_xc.c

XC_FILES   += dtm/verno_xc.h

CLEANFILES += dtm/verno_xc.h \
              dtm/verno_xc.c \
              dtm/verno.gccxml
