nobase_colibri_include_HEADERS += reqh/reqh.h \
                                  reqh/reqh_service.h

colibri_libcolibri_la_SOURCES  += reqh/reqh.c \
                                  reqh/reqh_service.c
