nobase_mero_include_HEADERS += reqh/reqh.h \
                                  reqh/reqh_service.h \
                                  reqh/reqh_addb.h

mero_libmero_la_SOURCES  += reqh/reqh.c \
                                  reqh/reqh_service.c
