/* -*- C -*- */

/*
 * WARNING: this file is automatically generated
 * from reqh_fops.ff by fop2c. Do not edit.
 */

#include "lib/cdefs.h"
#include "fop/fop.h"
#include "reqh_fops_u.h"
#include "net/usunrpc/usunrpc.h"

static bool_t uxdr_c2_reqh_error_rep(XDR *xdrs, struct c2_reqh_error_rep *crer)
{
	extern struct c2_fop_type_format c2_reqh_error_rep_tfmt;
	return c2_fop_type_uxdr(c2_reqh_error_rep_tfmt.ftf_out, xdrs, crer);
}

struct c2_fop_memlayout c2_reqh_error_rep_memlayout = {
	.fm_sizeof = sizeof (struct c2_reqh_error_rep),
	.fm_uxdr = (xdrproc_t)uxdr_c2_reqh_error_rep,
	.fm_child = {
		{ offsetof(struct c2_reqh_error_rep, sierr_rc) },
	}
};



/* 
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
