/* -*- C -*- */
#ifndef __COLIBRI_REQH_FOPS_UDEF_H__
#define __COLIBRI_REQH_FOPS_UDEF_H__

/*
 * WARNING: this file is automatically generated
 * from reqh_fops.ff by fop2c. Do not edit.
 */

#include "lib/cdefs.h"
#include "fop/fop.h"
#include <rpc/rpc.h>

struct c2_reqh_error_rep {
	uint32_t             rerr_rc;
};

extern struct c2_fop_memlayout c2_reqh_error_rep_memlayout;

/* __COLIBRI_REQH_FOPS_UDEF_H__ */
#endif

/* 
 *  Local variables:
 *  c-indentation-style: "K&R"
 *  c-basic-offset: 8
 *  tab-width: 8
 *  fill-column: 80
 *  scroll-step: 1
 *  End:
 */
