nobase_mero_include_HEADERS += sns/cm/st/trigger_fop.h

mero_libmero_la_SOURCES  += sns/cm/st/trigger_fop.h \
                            sns/cm/st/trigger_fom.h \
                            sns/cm/st/trigger_fom.c \
                            sns/cm/st/trigger_fop_xc.c

sns_cm_st_m0repair_SOURCES = sns/cm/st/repair_cli.c

XC_FILES   += sns/cm/st/trigger_fop_xc.h

CLEANFILES += sns/cm/st/trigger_fop_xc.h \
              sns/cm/st/trigger_fop_xc.c \
              sns/cm/st/trigger_fop.gccxml
