nobase_mero_include_HEADERS += sns/cm/st/trigger_fop.h

mero_libmero_la_SOURCES  += sns/cm/st/trigger_fop.h \
                                  sns/cm/st/trigger_fom.c \
                                  sns/cm/st/trigger_fop_ff.c

sns_cm_st_repair_SOURCES = sns/cm/st/repair_cli.c

EXTRA_DIST += sns/cm/st/trigger_fop.ff

FF_FILES   += sns/cm/st/trigger_fop_ff.h

CLEANFILES += sns/cm/st/trigger_fop_ff.h \
              sns/cm/st/trigger_fop_ff.c
