ut_libmero_ut_la_SOURCES += clovis/ut/clovis.c clovis/ut/clovis_obj.c clovis/ut/io_dummy.c \
			    clovis/ut/io_req.c clovis/ut/io_req_fop.c clovis/ut/io_pargrp.c \
			    clovis/ut/io_nw_xfer.c clovis/ut/clovis_io.c \
			    clovis/ut/clovis_idx.c clovis/ut/clovis_osync.c \
			    clovis/ut/clovis_idx_kvs.c clovis/ut/clovis.h
