nobase_mero_include_HEADERS += \
                            cas/cas.h

mero_libmero_la_SOURCES  += \
                            cas/cas_xc.c \
                            cas/service.c

XC_FILES += \
                            cas/cas_xc.h
